import React from 'react';

export interface Station {
  id: string;
  name: string;
  description: string;
  bikes: number;
  electricBikes: number;
  docks: number;
  status: 'available' | 'low-stock' | 'empty';
  distance: string;
  location: string;
  safetyScore: string;
  lat: number;
  lng: number;
}

export const STATIONS: Station[] = [
  {
    id: '1',
    name: 'KL Sentral',
    description: 'Main Transport Hub',
    bikes: 12,
    electricBikes: 4,
    docks: 8,
    status: 'available',
    distance: '0.4 km',
    location: 'Main Entrance, Level 1',
    safetyScore: 'Excellent (4.9/5.0)',
    lat: 3.1344,
    lng: 101.6861,
  },
  {
    id: '2',
    name: 'Pasar Seni',
    description: 'Cultural Hub',
    bikes: 8,
    electricBikes: 2,
    docks: 12,
    status: 'available',
    distance: '1.2 km',
    location: 'LRT Station Entrance',
    safetyScore: 'Good (4.5/5.0)',
    lat: 3.1425,
    lng: 101.6955,
  },
  {
    id: '3',
    name: 'Bukit Bintang',
    description: 'Shopping District',
    bikes: 2,
    electricBikes: 0,
    docks: 18,
    status: 'low-stock',
    distance: '2.1 km',
    location: 'Pavilion KL Side Entrance',
    safetyScore: 'Excellent (4.8/5.0)',
    lat: 3.1478,
    lng: 101.7137,
  },
  {
    id: '4',
    name: 'TRX',
    description: 'Financial Center',
    bikes: 0,
    electricBikes: 0,
    docks: 20,
    status: 'empty',
    distance: '2.8 km',
    location: 'Exchange 106 Plaza',
    safetyScore: 'Excellent (5.0/5.0)',
    lat: 3.1422,
    lng: 101.7185,
  },
  {
    id: '5',
    name: 'KLCC',
    description: 'Twin Towers',
    bikes: 15,
    electricBikes: 6,
    docks: 5,
    status: 'available',
    distance: '3.2 km',
    location: 'Suria KLCC Park Entrance',
    safetyScore: 'Excellent (4.9/5.0)',
    lat: 3.1579,
    lng: 101.7116,
  },
  {
    id: '6',
    name: 'Ampang Park',
    description: 'Business District',
    bikes: 10,
    electricBikes: 3,
    docks: 7,
    status: 'available',
    distance: '3.5 km',
    location: 'LRT Ampang Park Entrance',
    safetyScore: 'Excellent (4.7/5.0)',
    lat: 3.1598,
    lng: 101.7191,
  },
  {
    id: '7',
    name: 'Titiwangsa',
    description: 'Park & Transit Hub',
    bikes: 20,
    electricBikes: 8,
    docks: 10,
    status: 'available',
    distance: '4.2 km',
    location: 'Monorail Station Exit',
    safetyScore: 'Good (4.3/5.0)',
    lat: 3.1737,
    lng: 101.6953,
  },
  {
    id: '8',
    name: 'Wangsa Maju',
    description: 'Residential Hub',
    bikes: 5,
    electricBikes: 1,
    docks: 15,
    status: 'available',
    distance: '8.5 km',
    location: 'LRT Wangsa Maju Entrance',
    safetyScore: 'Good (4.2/5.0)',
    lat: 3.2057,
    lng: 101.7315,
  },
  {
    id: '9',
    name: 'Maluri',
    description: 'Shopping & Transit',
    bikes: 14,
    electricBikes: 5,
    docks: 6,
    status: 'available',
    distance: '4.8 km',
    location: 'MRT Maluri Entrance',
    safetyScore: 'Good (4.4/5.0)',
    lat: 3.1274,
    lng: 101.7271,
  },
  {
    id: '10',
    name: 'Cochrane',
    description: 'IKEA & MyTOWN',
    bikes: 18,
    electricBikes: 7,
    docks: 12,
    status: 'available',
    distance: '4.5 km',
    location: 'MRT Cochrane Exit A',
    safetyScore: 'Excellent (4.8/5.0)',
    lat: 3.1328,
    lng: 101.7231,
  },
  {
    id: '11',
    name: 'Bandar Utama',
    description: '1 Utama Shopping',
    bikes: 25,
    electricBikes: 10,
    docks: 15,
    status: 'available',
    distance: '12.2 km',
    location: 'MRT Bandar Utama Exit',
    safetyScore: 'Excellent (4.9/5.0)',
    lat: 3.1472,
    lng: 101.6111,
  },
  {
    id: '12',
    name: 'Phileo Damansara',
    description: 'Office District',
    bikes: 6,
    electricBikes: 2,
    docks: 14,
    status: 'available',
    distance: '10.5 km',
    location: 'MRT Phileo Damansara Entrance',
    safetyScore: 'Good (4.5/5.0)',
    lat: 3.1294,
    lng: 101.6425,
  },
  {
    id: '13',
    name: 'Bangsar',
    description: 'Lifestyle Hub',
    bikes: 9,
    electricBikes: 3,
    docks: 11,
    status: 'available',
    distance: '3.8 km',
    location: 'LRT Bangsar Entrance',
    safetyScore: 'Excellent (4.7/5.0)',
    lat: 3.1274,
    lng: 101.6781,
  },
  {
    id: '14',
    name: 'Abdullah Hukum',
    description: 'KL Eco City',
    bikes: 11,
    electricBikes: 4,
    docks: 9,
    status: 'available',
    distance: '4.1 km',
    location: 'LRT Abdullah Hukum Link Bridge',
    safetyScore: 'Excellent (4.8/5.0)',
    lat: 3.1184,
    lng: 101.6731,
  },
  {
    id: '15',
    name: 'Mid Valley',
    description: 'Mega Mall',
    bikes: 30,
    electricBikes: 12,
    docks: 20,
    status: 'available',
    distance: '4.0 km',
    location: 'KTM Mid Valley Entrance',
    safetyScore: 'Excellent (4.9/5.0)',
    lat: 3.1174,
    lng: 101.6771,
  },
  {
    id: '16',
    name: 'Chan Sow Lin',
    description: 'Industrial Hub',
    bikes: 4,
    electricBikes: 1,
    docks: 16,
    status: 'available',
    distance: '5.2 km',
    location: 'LRT Chan Sow Lin Exit',
    safetyScore: 'Fair (3.9/5.0)',
    lat: 3.1274,
    lng: 101.7141,
  },
  {
    id: '17',
    name: 'Sri Petaling',
    description: 'Residential Area',
    bikes: 7,
    electricBikes: 2,
    docks: 13,
    status: 'available',
    distance: '10.8 km',
    location: 'LRT Sri Petaling Entrance',
    safetyScore: 'Good (4.3/5.0)',
    lat: 3.0684,
    lng: 101.6881,
  },
  {
    id: '18',
    name: 'Bukit Jalil',
    description: 'Sports City',
    bikes: 15,
    electricBikes: 5,
    docks: 15,
    status: 'available',
    distance: '11.5 km',
    location: 'LRT Bukit Jalil Entrance',
    safetyScore: 'Excellent (4.7/5.0)',
    lat: 3.0584,
    lng: 101.6931,
  },
  {
    id: '19',
    name: 'Sungai Besi',
    description: 'Transit Point',
    bikes: 8,
    electricBikes: 2,
    docks: 12,
    status: 'available',
    distance: '12.0 km',
    location: 'LRT Sungai Besi Entrance',
    safetyScore: 'Good (4.1/5.0)',
    lat: 3.0644,
    lng: 101.7081,
  },
  {
    id: '20',
    name: 'Kajang',
    description: 'Satay Town',
    bikes: 10,
    electricBikes: 3,
    docks: 20,
    status: 'available',
    distance: '25.0 km',
    location: 'MRT Kajang Entrance',
    safetyScore: 'Good (4.2/5.0)',
    lat: 2.9824,
    lng: 101.7901,
  },
];

export interface Ride {
  id: string;
  from: string;
  to: string;
  date: string;
  time: string;
  duration: string;
  distance: string;
  cost: string;
  status: 'completed' | 'active';
}

export const RECENT_RIDES: Ride[] = [
  {
    id: 'KLR-88291',
    from: 'KLCC',
    to: 'Bukit Bintang',
    date: 'Oct 24, 2023',
    time: '14:20 PM',
    duration: '18 min',
    distance: '2.4 km',
    cost: 'RM 2.00',
    status: 'completed',
  },
  {
    id: 'KLR-88292',
    from: 'KL Sentral',
    to: 'Pasar Seni',
    date: 'Oct 22, 2023',
    time: '08:45 AM',
    duration: '25 min',
    distance: '3.8 km',
    cost: 'RM 3.00',
    status: 'completed',
  },
  {
    id: 'KLR-88293',
    from: 'TRX',
    to: 'Ampang Park',
    date: 'Oct 20, 2023',
    time: '18:10 PM',
    duration: '12 min',
    distance: '1.5 km',
    cost: 'RM 2.00',
    status: 'completed',
  },
];
